.github/workflows/build.yml
This PR fixes the GitHub pages build which was previously targeting the wrong branch. Some day we will probably rename the master branch, but for now, this gets the spec up and running.
=> Fix gh-pages

spec.bs
This PR introduces a monkey patch that modifies the CORP internal check to not short circuit allow for same-origin URLs if the request's destination is a fenced frame. This will ensure that fenced frames always act like cross-origin frames, regardless of the origin of its src attribute.
=> Add monkey patch for Cross-Origin Resource Policy Internal Check

spec.bs
Reverts WICG/fenced-frame#31
This is not necessary since the potential 1-bit leak that this is patching is not an issue. See this document for reasoning why:
https://docs.google.com/document/d/1wQTnfpksl8i-UxQ-1eoFvKtYIgv7RVCNnM42YbJVEYQ/edit?usp=sharing
=> Revert "Add monkey patch for Cross-Origin Resource Policy Internal Check"

spec.bs
This PR introduces a monkey patch that adds a new CSP directive, "fenced-frame-src". This copies most of its behavior from the already existing "frame-src" directive.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/34.html" title="Last updated on Jul 17, 2022, 10:20 PM UTC (8b2b847)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/34/28f6d0c...8b2b847.html" title="Last updated on Jul 17, 2022, 10:20 PM UTC (8b2b847)">Diff</a>
=> Add monkey patch for fenced-frame-src directive

explainer/README.md
This adds an explainer outlining a new API for fenced frames to tell if an opaque ads fenced frame will be allowed to load in a given context.
This change has gone through CMA pre-review and can be merged in.
=> add explainer for canLoadOpaqueURL() API

spec.bs
Would be useful in https://github.com/WICG/turtledove/pull/539 (and probably other places eventually).
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/fenced-frame/pull/75.html" title="Last updated on Apr 14, 2023, 12:26 AM UTC (edfda45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/75/4b6b5ec...miketaylr:edfda45.html" title="Last updated on Apr 14, 2023, 12:26 AM UTC (edfda45)">Diff</a>
=> Export fencedframe dfn

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/67.html" title="Last updated on Apr 17, 2023, 7:17 PM UTC (208b004)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/67/123ccb0...208b004.html" title="Last updated on Apr 17, 2023, 7:17 PM UTC (208b004)">Diff</a>
=> Elaborate on FencedFrameConfig

spec.bs
I think this PR makes things better and more explicit, but I believe things are still broken even after this. A few questions/points:
- In the `Fence` methods, should it ever be possible for `instance` to be null, as we check for in step 2? I think the `instance` that we check when retrieving the `Fence` object in the first place (https://wicg.github.io/fenced-frame/#dom-window-fence > Step 2) should be a sufficient gate, such that we don't have to check for _instance_ anymore inside the methods, right? The way I envision the ideal world here, is that because we have to support URN iframes, we make the "instance" retriever in both the `window.fence` getter and the `fence.*` methods both traverse upwards until they find a navigable with a non-null _instance_ and both reference that …
=> Introduce navigable's config instance

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/74.html" title="Last updated on Apr 30, 2023, 12:35 PM UTC (cad5853)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/74/0582b0e...cad5853.html" title="Last updated on Apr 30, 2023, 12:35 PM UTC (cad5853)">Diff</a>
=> Add permissions patches

spec.bs
We could alternatively rename the master branch to main and I think that would fix it too.
***
<a href="https://pr-preview.s3.amazonaws.com/caraitto/fenced-frame/pull/83.html" title="Last updated on May 2, 2023, 6:42 PM UTC (95fd52e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/83/99901d3...caraitto:95fd52e.html" title="Last updated on May 2, 2023, 6:42 PM UTC (95fd52e)">Diff</a>
=> [Spec] Fix broken link

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/78.html" title="Last updated on May 5, 2023, 4:01 PM UTC (bdd49d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/78/2aad9c7...bdd49d6.html" title="Last updated on May 5, 2023, 4:01 PM UTC (bdd49d6)">Diff</a>
=> Elaborate on event reporting

spec.bs
This PR finally specs the `config` IDL attribute assignment, making it the only entrypoint into HTML's `#navigate` algorithm. This PR also adds patches to the navigate algorithm, including the invocation to _find a config_ which may wait arbitrarily in the navigation process until the config is finalized and we can override the navigation URL to the actual mapped URL.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/84.html" title="Last updated on May 5, 2023, 10:10 PM UTC (2fdf0cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/84/5af7b1a...2fdf0cf.html" title="Last updated on May 5, 2023, 10:10 PM UTC (2fdf0cf)">Diff</a>
=> Spec config assignment and core #navigate algorithm changes

spec.bs
This supplements https://chromium-review.googlesource.com/c/chromium/src/+/4547401
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/88.html" title="Last updated on May 18, 2023, 3:22 PM UTC (cfdec94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/88/0f4d425...cfdec94.html" title="Last updated on May 18, 2023, 3:22 PM UTC (cfdec94)">Diff</a>
=> Remove FencedFrameConfig#url

spec.bs
This depends on `[=browsing context/fenced frame config instance=]` (instead of the current spec's `[=navigable/fenced frame config instance=]`), as introduced in https://github.com/WICG/fenced-frame/pull/90. Even though this PR only references that term editorially, until that PR is merged this build will fail.
This PR does _not yet_ assign the browsing context's fenced frame config instance. A subsequent PR will do this in the [document creation algorithm](https://html.spec.whatwg.org/multipage/document-lifecycle.html#initialise-the-document-object) by pulling the config instance off of the navigation params, whose member is introduced by this PR, and placing it on the browsing context that loads inside the fenced frame.
***
<a …
=> Assign config instance during navigation

spec.bs
Mind taking a look @inexorabletash? This addresses the title capitalization as well as the width/height feedback (making the IDL attributes link to the ones now defined in this section, which reflect the now-defined content attributes etc.)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/93.html" title="Last updated on May 24, 2023, 12:03 PM UTC (34ae4c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/93/f3d2d23...34ae4c6.html" title="Last updated on May 24, 2023, 12:03 PM UTC (34ae4c6)">Diff</a>
=> Address some early spec feedback

spec.bs
- Reword step 9 to make it clear that the starting point should be a navigable's parent OR a fenced navigable's unfenced parent.
- Reword step 9 to reference the unfenced parent algorithm instead of the traversable navigable's unfenced parent declaration.
- Fix formatting issues.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/100.html" title="Last updated on Jun 5, 2023, 8:04 PM UTC (75e4d0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/100/fb89d8c...75e4d0c.html" title="Last updated on Jun 5, 2023, 8:04 PM UTC (75e4d0c)">Diff</a>
=> Address issues with focus patches from spec review

spec.bs
I think it being a string was a boilerplate copy that I forgot to fix.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/103.html" title="Last updated on Jun 9, 2023, 7:39 PM UTC (4b08e56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/103/376d4d0...4b08e56.html" title="Last updated on Jun 9, 2023, 7:39 PM UTC (4b08e56)">Diff</a>
=> Interest group descriptor string -> origin

spec.bs
Oops, you need to tell it what config value to finalize with... unless you keep a reference to the original pending config, but I think this is simpler.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/104.html" title="Last updated on Jun 14, 2023, 6:11 PM UTC (2d773c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/104/2d2a330...2d773c8.html" title="Last updated on Jun 14, 2023, 6:11 PM UTC (2d773c8)">Diff</a>
=> Fix finalize config procedure

spec.bs
When navigating to a URL with a local scheme (URLs like about:blank), iframes clone their policy container from the policy container of the navigation's initiating document. We don't want fenced frames to be able to do that, since that will tell the fenced frame information about a policy container that lives past a fenced frame boundary. This PR adds a patch to stop that inheritance from happening.
(Implementation detail) Note that with the Chromium's MPArch implementation of fenced frames, we get that behavior for free because the initiator frame token is not passed in to the policy container builder during the navigation request. However, we want to make sure that any other implementations also have this behavior, which is why this patch is needed.
The main algorithm that is patched is …
=> Local scheme navigation policy container patch

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/71.html" title="Last updated on Jul 31, 2023, 4:54 PM UTC (ca2a489)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/71/fb89d8c...ca2a489.html" title="Last updated on Jul 31, 2023, 4:54 PM UTC (ca2a489)">Diff</a>
=> Add scroll bubbling monkeypatches

explainer/use_cases.md
Update the explainer to include steps on how to get Chrome working with default mode fenced frames, as well as a quick example on getting a fenced frame loaded through default mode.
=> Add tutorial for default fenced frames in explainer

spec.bs
- Adds "attempt to send an automatic beacon" algorithm
- Adds patch to "attempt to populate the history entry's document" to invoke "attempt to send an automatic beacon".
- Adds "once" parameter to the FenceEvent dictionary and automatic beacon data struct.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/109.html" title="Last updated on Aug 16, 2023, 9:45 PM UTC (9477e54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/109/eb6b50e...9477e54.html" title="Last updated on Aug 16, 2023, 9:45 PM UTC (9477e54)">Diff</a>
=> Add automatic beacon patches

spec.bs
This PR:
- Makes `FencedFrameConfig` objects serializable and defines serializing/deserializing steps for it.
- Removes `config` as an attribute of a `FencedFrameConfig`, replacing it with a clone of the values it needs from the internal `Fenced Frame Config` struct.
- Passes in the `sharedStorageContext` directly to the `navigate` algorithm, which will read the `sharedStorageContext` from the IDL object to the `embedder shared storage context` in the `Fenced Frame Config` struct. This is done since we are no longer writing directly to the `Fenced Frame Config` struct in the `setSharedStorageContext()` algorithm.
- Modifies `getNestedConfigs()` to account for the changes to `FencedFrameConfig`.
- Update the step number for the `navigate` step that goes in parallel.
- Update the …
=> Make FencedFrameConfig IDL objects serializable

explainer/integration_with_web_platform.md
The decision has been made to not fence Screen interface properties within fenced frames, see [doc](https://docs.google.com/document/d/1sZOgnAUsIzNHOs_VVWF92er1jXmNCcv6k3vvOvixeFc/edit?usp=sharing) for rationale. This PR documents that decision explicitly.
=> Add Screen interface integration info.

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/117.html" title="Last updated on Sep 22, 2023, 2:37 PM UTC (6600ce4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/117/cf06e42...6600ce4.html" title="Last updated on Sep 22, 2023, 2:37 PM UTC (6600ce4)">Diff</a>
=> Spec deprecatedReplaceInURN

explainer/integration_with_web_platform.md
Based on https://crbug.com/1307642 and corresponding discussion, we need to specify how deviceID from the MediaDevices interface is partitioned within fenced frames.
=> Add MediaDevices info to web platform integration.

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/113.html" title="Last updated on Sep 26, 2023, 4:20 PM UTC (29bc781)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/113/3b93e20...29bc781.html" title="Last updated on Sep 26, 2023, 4:20 PM UTC (29bc781)">Diff</a>
=> Spec reportEvent to custom destination URLs with macro substitution

spec.bs
Automatic beacons will now send to all URLs that registered with the reserved.top_navigation event type, regardless of what data was set when calling setReportEventDataForAutomaticBeacons(). However, automatic beacon data will only be included in the beacon if the beacon's destination is specified in the destination field when calling setReportEventDataForAutomaticBeacons().
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/122.html" title="Last updated on Sep 22, 2023, 3:15 PM UTC (d598d24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/122/bd99c82...d598d24.html" title="Last updated on Sep 22, 2023, 3:15 PM UTC (d598d24)">Diff</a>
=> Update automatic beacon algorithm to send to all registered URLs

spec.bs
This is migrated from the monkeypatches in attribution reporting API spec: https://wicg.github.io/attribution-reporting-api/#fenced-frame-monkeypatches
Also spec'ed the integration for automatic beacon.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/fenced-frame/pull/127.html" title="Last updated on Oct 12, 2023, 3:30 PM UTC (a7b975f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/127/ed8c323...linnan-github:a7b975f.html" title="Last updated on Oct 12, 2023, 3:30 PM UTC (a7b975f)">Diff</a>
=> Spec for attribution reporting integration

spec.bs
These are only being used inside the fenced frame spec, so they can be safely unexported.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/132.html" title="Last updated on Oct 27, 2023, 6:15 PM UTC (1d3c703)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/132/94b48b1...1d3c703.html" title="Last updated on Oct 27, 2023, 6:15 PM UTC (1d3c703)">Diff</a>
=> Unexport destination events

spec.bs
This PR does a few things to allow the new automatic beacon types:
- ~~Creates a new "valid automatic beacon event types" list that contains the start and commit beacon types.~~
-  Creates a new implicit enumerated type for the automatic beacon event types. This contains the start and commit beacon types.
- Creates a new "automatic beacon event" to be used for automatic beacons instead of "destination enum event", which contains the aforementioned implicit enumerated event type.
- Splits out automatic beacon data into its own struct.
- Turns the fenced frame reporter's automatic beacon data into a mapping to match the implementation.
- Passes "reserved.top_navigation_commit" as a parameter when calling the automatic beacon algorithm from its existing place at navigation commit.
- Also …
=> Spec reserved.top_navigation_start and reserved.top_navigation_commit

spec.bs
This PR specs the event reporting algorithms for ad component frames, according to the [Protected Audience explainer](https://github.com/WICG/turtledove/blob/main/Fenced_Frames_Ads_Reporting.md#design-1).
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/135.html" title="Last updated on Dec 18, 2023, 9:10 PM UTC (63cf39f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/135/79fad8a...xiaochen-z:63cf39f.html" title="Last updated on Dec 18, 2023, 9:10 PM UTC (63cf39f)">Diff</a>
=> Add ad component event reporting algorithms.

spec.bs
Reporting an event through the `window.fence.reportEvent()` call should not be allowed to work if it's passed in a "reserved." event type.
This PR also exports `automatic beacon event type`, which will be used by the TURTLEDOVE spec for a similar patch to `registerAdBeacon()`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/134.html" title="Last updated on Dec 18, 2023, 7:24 PM UTC (b94150e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/134/79fad8a...b94150e.html" title="Last updated on Dec 18, 2023, 7:24 PM UTC (b94150e)">Diff</a>
=> Prevent reserved beacons from being sent manually.

spec.bs
This updates the line that clears out automatic beacon data whose `once=True` to use the new automatic beacon data map that was added in https://github.com/WICG/fenced-frame/pull/133.
One concern I have about this is whether or not the [get the automatic beacon data mapping to use](https://wicg.github.io/fenced-frame/#get-the-automatic-beacon-data-mapping-to-use) algorithm is building a map of references to or copies of the original mapping. If it's the latter, then we'll need to do further refactoring to make sure that the things in the various mappings can be modified by the "maybe send automatic beacon" algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/139.html" title="Last updated on Jan 18, 2024, 11:31 PM UTC (53608f0)">Preview</a> | <a …
=> Fix failing build caused by stale reference

spec.bs
This adds a new "use cases" subsection to the "Fenced frame configs" section. This outlines 2 use cases (ad rendering + personalized payment button) and how it relates to the different ways to build a fenced frame config. They also go into privacy stories for both use cases.
I had also considered putting this in the main "Introduction" section, but decided it was both better to keep that section brief and to put this in a place where the concept of a "fenced frame config" had already been introduced.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/142.html" title="Last updated on Mar 13, 2024, 11:18 PM UTC (77fcc84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/142/d6a5a54...77fcc84.html" title="Last updated on Mar 13, 2024, 11:18 PM …
=> Add a non-normative use cases section

spec.bs
The automatic beacon algorithm uses an automatic beacon data map that is built off of the data maps in the initiator frame's ancestors. This PR makes more clear that the data map should be stored as references to the original automatic beacon data maps, since it is needed to make modifications while running the automatic beacon algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/141.html" title="Last updated on Jan 22, 2024, 9:21 PM UTC (d24816e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/141/d6a5a54...d24816e.html" title="Last updated on Jan 22, 2024, 9:21 PM UTC (d24816e)">Diff</a>
=> Ensure the automatic beacon data map is a reference

spec.bs
`csp-transparent-url` was split off into `csp-allowed-transparent` and `csp-blocked-transparent`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/145.html" title="Last updated on Mar 28, 2024, 6:41 PM UTC (fed7be4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/145/fd26825...fed7be4.html" title="Last updated on Mar 28, 2024, 6:41 PM UTC (fed7be4)">Diff</a>
=> Fix build failure caused by renamed WPT

explainer/fenced_frames_with_local_unpartitioned_data_access.md
Now that we've solidified some of the API designs, we should have more details about them in the explainer where necessary. Getting from shared storage is pretty straightforward, but the click listener API needs an explicit description of its API surface. 
In addition, I've added an end-to-end example of how all of our API surfaces can be combined for a real-world use case of personalized payment buttons.
=> Add specific click API details, plus a code example

spec.bs
Reporting beacons can now be sent with `window.fence.reportEvent()` from documents that are cross origin to a fenced frame config's mapped URL. To do this, there must be opt-in from both the document created with the FencedFrameConfig as well as the cross-origin document that wants to send the beacon. The document created with the FencedFrameConfig opts in with a new "Allow-Cross-Origin-Event-Reporting=true" response header. The cross-origin document opts in by calling `reportEvent()` with the `crossOriginExposed=true` parameter.
This PR updates the spec to match that behavior. More specifically:
- Updates the FenceEvent IDL to match the [current .idl file](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/fenced_frame/fence_event.idl) on the …
=> Spec cross-origin reportEvent() support

spec.bs
This issue was brought up in https://github.com/WICG/fenced-frame/issues/158.
This PR adds official definitions for the `Allow-Fenced-Frame-Automatic-Beacons` and the `Allow-Cross-Origin-Event-Reporting` response headers that are used for cross-origin opt in for their respective features.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/159.html" title="Last updated on May 21, 2024, 12:04 PM UTC (bff5d37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/159/dbb22ca...bff5d37.html" title="Last updated on May 21, 2024, 12:04 PM UTC (bff5d37)">Diff</a>
=> Add definitions for event reporting opt in headers

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/JensenPaul/fenced-frame/pull/162.html" title="Last updated on May 31, 2024, 6:51 PM UTC (53bac09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/162/e67a4f9...JensenPaul:53bac09.html" title="Last updated on May 31, 2024, 6:51 PM UTC (53bac09)">Diff</a>
=> Fix TODO for calling "on navigate callback"

spec.bs
Addresses https://github.com/WICG/turtledove/issues/1174
***
<a href="https://pr-preview.s3.amazonaws.com/HabibiYou/fenced-frame/pull/163.html" title="Last updated on Jun 4, 2024, 2:56 PM UTC (162281a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/163/e67a4f9...HabibiYou:162281a.html" title="Last updated on Jun 4, 2024, 2:56 PM UTC (162281a)">Diff</a>
=> Spec adAuctionComponents

spec.bs
This CL does the following:
- Specs out the "sandbox" attribute in the `fencedframe` element.
- Specs out the `fencedframe sandboxing flag set` to match the [iframe equivalent](https://html.spec.whatwg.org/multipage/browsers.html#iframe-sandboxing-flag-set).
- Specs out the behavior that ensures that a fenced frame's active sandboxing flag set is at least as restrictive as the fenced frame config's [effective sandboxing flags](https://wicg.github.io/fenced-frame/#fenced-frame-config-effective-sandbox-flags).
- Specs out the behavior that a fenced frame cannot load if the final sandboxing flag set is more restrictive than the [effective sandboxing flags](https://wicg.github.io/fenced-frame/#fenced-frame-config-effective-sandbox-flags).
Follow-up PRs will need to be done for the following: …
=> [Spec] Add sandbox attribute + handling

spec.bs
This would be beneficial to tell the reporting origin that attribution reporting is not supported, as opposed to letting it assume it can still register triggers.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/fenced-frame/pull/177.html" title="Last updated on Aug 15, 2024, 5:25 PM UTC (9851b18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/177/c799ffe...linnan-github:9851b18.html" title="Last updated on Aug 15, 2024, 5:25 PM UTC (9851b18)">Diff</a>
=> Set attribution reporting headers even if there's no supported registrar

spec.bs
The IDL containerWidth, containerHeight, contentWidth, and contentHeight attributes not actually implemented in Chromuim, so we should remove them.
Additionally, the internal fenced frame config struct does not implement container size, only content size. So we should remove that as well.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/182.html" title="Last updated on Aug 29, 2024, 5:37 PM UTC (7a51c0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/182/c799ffe...VergeA:7a51c0e.html" title="Last updated on Aug 29, 2024, 5:37 PM UTC (7a51c0e)">Diff</a>
=> Remove unused config size attributes

spec.bs
Follow-up to https://github.com/WICG/fenced-frame/pull/182
Along with the unused IDL size attributes, I also removed the internal fenced frame config container size definition. I was mistaken about it being vestigial (I missed a reference to it in the implementation when I was originally deciding to remove it, so I didn't see it was actively used). 
The Protected Audience spec depended on the field, and I broke their build: https://github.com/WICG/turtledove/pull/1270#issuecomment-2332092944
This change re-adds the container size definition to un-break things.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/187.html" title="Last updated on Sep 5, 2024, 5:43 PM UTC (38e8eb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/187/a8ec772.. …
=> Re-add fenced frame config internal container size.

spec.bs
`Process an attribution eligible response` interface was changed in  https://github.com/WICG/attribution-reporting-api/pull/1238.
***
<a href="https://pr-preview.s3.amazonaws.com/linnan-github/fenced-frame/pull/150.html" title="Last updated on Aug 14, 2024, 2:52 PM UTC (bef63a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/150/c799ffe...linnan-github:bef63a5.html" title="Last updated on Aug 14, 2024, 2:52 PM UTC (bef63a5)">Diff</a>
=> Udpate spec for processing attribution eligible response

spec.bs
https://github.com/WICG/PEPC/ would like to reference this term, so now that it has official consumers, I think exporting it seems reasonable.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/190.html" title="Last updated on Sep 12, 2024, 2:10 PM UTC (33119c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/190/c10d8f6...33119c6.html" title="Last updated on Sep 12, 2024, 2:10 PM UTC (33119c6)">Diff</a>
=> Export `fenced navigable`

spec.bs
The existing spec results in a fenced frame navigating directly to the `url` stored in a `FencedFrameConfig` IDL object when navigating to a config built with the `FencedFrameConfig(url)` default constructor. This results in a `fenced frame config` and `fenced frame config instance` not being created for the fenced frame, cutting off the internal document from `window.fence`.
This PR fixes that in the following ways:
- Modifies the `FencedFrameConfig(url)` constructor to also create a `fenced frame config` and add it to the navigable's `fenced frame config mapping`.
- Unconditionally passes in the `FencedFrameConfig`'s `urn` when navigating the internal document, ensuring that the navigation will find the associated `fenced frame config`, and instantiate a `fenced frame config instance` …
=> [Spec] Fix navigation from the default constructor not installing a fenced frame config.

spec.bs
This adds event handlers for `onfencedtreeclick`, and describes the algorithm for `window.fence.notifyEvent()`, which fires `fencedtreeclick` events from the fenced frame's document to the `HTMLFencedFrameElement` in the embedder.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/156.html" title="Last updated on Oct 21, 2024, 4:40 PM UTC (160aadd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/156/73d37f8...VergeA:160aadd.html" title="Last updated on Oct 21, 2024, 4:40 PM UTC (160aadd)">Diff</a>
=> Spec for window.fence.notifyEvent and onfencedtreeclick

spec.bs
Because WebRTC's RTCPeerConnection interface is disallowed in fenced frames, we need to patch the WebRTC spec to throw an exception in the constructor. This patch also introduces the a "fenced navigable ancestor" algorithm that can be used to determine if a given document is nested in a fenced frame tree. This mechanism is used to trigger the constructor error.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/197.html" title="Last updated on Nov 8, 2024, 9:03 PM UTC (b6479f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/197/01cf852...VergeA:b6479f9.html" title="Last updated on Nov 8, 2024, 9:03 PM UTC (b6479f9)">Diff</a>
=> Add RTCPeerConnection constructor error to spec.

spec.bs
This is a rewrite of #174, converting the rough outline for the _unfencedTop navigation target spec into a formal patch.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/200.html" title="Last updated on Nov 21, 2024, 3:22 PM UTC (c44f744)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/200/a22434f...VergeA:c44f744.html" title="Last updated on Nov 21, 2024, 3:22 PM UTC (c44f744)">Diff</a>
=> Add spec for _unfencedTop navigation target.

explainer/fenced_frames_with_local_unpartitioned_data_access.md
We've made 2 recent changes to the "fenced frames with local unpartitioned access" feature that should be documented in the explainer:
1. Reading from unpartitioned storage will be gated by the new `fenced-unpartitioned-storage-read` Permissions Policy directive 
1. User activation will be propagated to the embedder when `window.fence.notifyEvent()` executes successfully
=> Add permissions policy and UA behavior to unpartitioned access doc.

spec.bs
After untrusted network access has been disabled in a fenced frame via disableUntrustedNetwork(), script running in the frame will gain access to new powerful APIs. This patch provides an algorithm that other specs can use when implementing methods that should only succeed in a fenced frame with network access revoked.
Currently, the only method that will rely on this algorithm is SharedStorage.get(), which is implemented in the Shared Storage draft spec. I'm planning to update that spec separately after this PR merges.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/204.html" title="Last updated on Jan 14, 2025, 7:16 PM UTC (9fa9fbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/204/ffd3d63...VergeA:9fa9fbc.html" title="Last …
=> Add spec for APIs gated on network revocation.

explainer/fenced_frames_with_local_unpartitioned_data_access.md
This section contains command line flags to enable the local unpartitioned data access functionality in Chromium, and links to the demo sites we created for TPAC. This will make it easier for interested folks to test out the personalized payments use case on Chrome Canary.
=> Add demo section to local unpartitioned access explainer.

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/148.html" title="Last updated on Jan 21, 2025, 1:29 PM UTC (82f21b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/148/82a9f09...82f21b3.html" title="Last updated on Jan 21, 2025, 1:29 PM UTC (82f21b3)">Diff</a>
=> Spec "disable embedder-initiated nested fenced frame navigations after disabling untrusted network"

spec.bs
This PR makes the following changes
- Add fully active document checks in `window.fence` methods as they appear in the associated implementation.
- Move the `{{SecurityError}}` check in `disableUntrustedNetwork()` to the newly added active document check.
- Have all instances of `throw` link to the [throw definition](https://webidl.spec.whatwg.org/#dfn-throw).
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/209.html" title="Last updated on Feb 4, 2025, 7:15 PM UTC (13f22b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/209/1c78202...13f22b3.html" title="Last updated on Feb 4, 2025, 7:15 PM UTC (13f22b3)">Diff</a>
=> Check that document is fully active for window.fence methods

spec.bs
This ensures that the following things happen for both `WebTransport` and `WebSocket` objects:
- All open connections associated with a context are closed when untrusted network access is revoked.
- New connections cannot be created after network access is revoked.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/206.html" title="Last updated on Feb 19, 2025, 2:27 AM UTC (997d803)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/206/82a9f09...997d803.html" title="Last updated on Feb 19, 2025, 2:27 AM UTC (997d803)">Diff</a>
=> [Spec] Network revocation patches for WebSocket and WebTransport APIs

spec.bs
Fix spec build failure #211 
The current `[=visibilities=]` is referencing https://www.w3.org/TR/CSS22/visufx.html#propdef-visibility, which is incorrect. 
It should be `[=fencedframeconfig/visibilities=]` which references:
https://github.com/WICG/fenced-frame/blob/6fa197f163e3b0defbb925e95e8aefe83f804e7c/spec.bs#L793-L794
Also add the reference to the other "visibilities" in the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/212.html" title="Last updated on Feb 24, 2025, 3:21 PM UTC (0d38af5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/212/6fa197f...xiaochen-z:0d38af5.html" title="Last updated on Feb 24, 2025, 3:21 PM UTC (0d38af5)">Diff</a>
=> Fix spec build failure due to visibilities ref

spec.bs
fix: #205
This PR only implements the change in algorithm "recalculate the untrusted network status of all fenced frame descendants".
The part that this algorithm should be called whenever a navigation commits will be done in a follow-up PR. I'm still investigating how to spec this. See previous [comment](https://github.com/WICG/fenced-frame/pull/176#discussion_r1881105124) on this.
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/210.html" title="Last updated on Feb 25, 2025, 2:37 PM UTC (ced0b67)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/210/fa4ec2c...xiaochen-z:ced0b67.html" title="Last updated on Feb 25, 2025, 2:37 PM UTC (ced0b67)">Diff</a>
=> Spec descendant frames' ongoing navigations block disableUntrustedNetwork promise from being resolved

spec.bs
This spec patch does the following:
- Modifies the "generate and queue a report" to early return if invoked from documents within a fenced frame tree with its network access revoked.
- Modifies the Webpackage signed exchange reporting API to only queue a report if the request's associated partition nonce is not one of the revoked nonces.
- Note that this spec is on hold and most likely not going to become a standard, but we are still adding this patch in to cover all our bases.
- Modifies the "must be blocked due to a revoked partition nonce" algorithm to look for the nonce and URL in the request object, rather than expecting one to be provided.
- This should be fine because the algorithm that [pulls the nonce from the request object](https://fetch.spec.whatwg.org/#request-determine-the-ne …
=> [Spec] Network revocation patches for Reporting API and Signed Exchange Reports

spec.bs
Fix #214.
After some investigations, it seems adding the recalculation step in `set the ongoing navigation` algorithm makes the most sense.
The only similar feature in the current standard is the navigation API, which has two [promises](https://html.spec.whatwg.org/#navigation-api-method-tracker-committed). Their resolution or rejection are done when certain navigation events are fired. See:
* [resolve the finished promise](https://html.spec.whatwg.org/#resolve-the-finished-promise)
* [reject the finished promise](https://html.spec.whatwg.org/#reject-the-finished-promise)
However, these promises are only relevant for navigations that are intercepted by the navigation API. When a cross-site navigation is not intercepted by the navigation API, no resolution or rejection steps are run on the …
=> Recalculate network status when navigation ends

spec.bs
`history-length-outer-page-navigation-not-reflected-in-fenced-nested-iframe` was split off from `history-length-outer-page-navigation-not-reflected-in-fenced`. Add the new test to the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/229.html" title="Last updated on Apr 4, 2025, 6:05 PM UTC (25e3563)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/229/c628f90...25e3563.html" title="Last updated on Apr 4, 2025, 6:05 PM UTC (25e3563)">Diff</a>
=> Add new history WPT
