WICG/fenced-frame

explainer/modes.md

the url should only be an https, localhost or about:blank.

added url types restrictions

---

spec.bs

Add a new "fencedframe" request destination that has the same exact properties as the "iframe" request destination.

Add monkey patch to add "fencedframe" request destination

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/fenced-frame/pull/52.html#ref-for-concept-element-dom" title="Last updated on Sep 21, 2022, 8:02 PM UTC (ff2a48d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/52/b829f69...jyasskin:ff2a48d.html" title="Last updated on Sep 21, 2022, 8:02 PM UTC (ff2a48d)">Diff</a>

Fix a markup error

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/62.html" title="Last updated on Mar 15, 2023, 7:42 PM UTC (8160fa7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/62/3988498...8160fa7.html" title="Last updated on Mar 15, 2023, 7:42 PM UTC (8160fa7)">Diff</a>

Spec: Nested navigable insertion & navigation

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/64.html" title="Last updated on Mar 21, 2023, 6:45 PM UTC (fd3003d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/64/683e6a5...fd3003d.html" title="Last updated on Mar 21, 2023, 6:45 PM UTC (fd3003d)">Diff</a>

Introduce fenced frame config struct

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/66.html" title="Last updated on Apr 7, 2023, 2:13 PM UTC (50be756)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/66/0e29df2...50be756.html" title="Last updated on Apr 7, 2023, 2:13 PM UTC (50be756)">Diff</a>

Update Fence IDL

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/69.html" title="Last updated on Apr 10, 2023, 9:21 PM UTC (5120167)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/69/097ccdd...5120167.html" title="Last updated on Apr 10, 2023, 9:21 PM UTC (5120167)">Diff</a>

Spec COOP/COEP integration

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/68.html" title="Last updated on Apr 17, 2023, 12:08 PM UTC (2e331e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/68/4b6b5ec...2e331e6.html" title="Last updated on Apr 17, 2023, 12:08 PM UTC (2e331e6)">Diff</a>

Add focusing changes + monkeypatches

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/77.html" title="Last updated on Apr 19, 2023, 9:22 AM UTC (8b9961e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/77/93245cf...8b9961e.html" title="Last updated on Apr 19, 2023, 9:22 AM UTC (8b9961e)">Diff</a>

FencedFrameConfig IDL fixes

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/79.html" title="Last updated on Apr 20, 2023, 6:45 PM UTC (29c8543)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/79/e3c694e...29c8543.html" title="Last updated on Apr 20, 2023, 6:45 PM UTC (29c8543)">Diff</a>

Add WPT block for COOP/COEP tests

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/72.html" title="Last updated on Apr 24, 2023, 10:17 PM UTC (ddb74bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/72/4b6b5ec...ddb74bc.html" title="Last updated on Apr 24, 2023, 10:17 PM UTC (ddb74bc)">Diff</a>

Add CSP and CSPEE patches

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/81.html" title="Last updated on Apr 27, 2023, 2:30 PM UTC (8195b9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/81/5aa1668...8195b9a.html" title="Last updated on Apr 27, 2023, 2:30 PM UTC (8195b9a)">Diff</a>

Rename and document fenced frame config's required permissions

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/85.html" title="Last updated on May 9, 2023, 5:57 PM UTC (54e2730)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/85/9e6752c...54e2730.html" title="Last updated on May 9, 2023, 5:57 PM UTC (54e2730)">Diff</a>

Make "store a pending config" return the urn

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/87.html" title="Last updated on May 16, 2023, 11:20 AM UTC (78f5b0f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/87/ad5e360...78f5b0f.html" title="Last updated on May 16, 2023, 11:20 AM UTC (78f5b0f)">Diff</a>

Add note about pending configs

---

spec.bs

This PR is related to https://github.com/WICG/fenced-frame/pull/90.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/91.html" title="Last updated on May 22, 2023, 2:54 PM UTC (28acd3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/91/204e674...28acd3b.html" title="Last updated on May 22, 2023, 2:54 PM UTC (28acd3b)">Diff</a>

Force embedder-initiated BCG swaps

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/89.html" title="Last updated on May 22, 2023, 5:38 PM UTC (fdae7dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/89/204e674...fdae7dd.html" title="Last updated on May 22, 2023, 5:38 PM UTC (fdae7dd)">Diff</a>

Add "on navigate callback"

---

spec.bs

This PR address much of the editorial feedback received from the pre-Chromium-I2S review.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/95.html" title="Last updated on May 25, 2023, 4:03 PM UTC (957c439)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/95/45b6a96...957c439.html" title="Last updated on May 25, 2023, 4:03 PM UTC (957c439)">Diff</a>

Editorial: Address more early spec feedback

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/97.html" title="Last updated on Jun 1, 2023, 10:20 PM UTC (296057b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/97/ff20416...296057b.html" title="Last updated on Jun 1, 2023, 10:20 PM UTC (296057b)">Diff</a>

Port some intro from the explainer

---

spec.bs

[Editorial spec feedback](https://docs.google.com/document/d/14nM7iLVXWoNKNajznUMIvF7A_W4WwG3CAXYoYJpTp1I/edit).
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/98.html" title="Last updated on Jun 2, 2023, 2:06 AM UTC (5053eef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/98/8c8d9ec...5053eef.html" title="Last updated on Jun 2, 2023, 2:06 AM UTC (5053eef)">Diff</a>

Address more editorial feedback

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/99.html" title="Last updated on Jun 2, 2023, 11:49 AM UTC (fe25191)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/99/baf75f5...fe25191.html" title="Last updated on Jun 2, 2023, 11:49 AM UTC (fe25191)">Diff</a>

Last round of small editorial feedback

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/101.html" title="Last updated on Jun 6, 2023, 12:14 PM UTC (81efe41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/101/fb89d8c...81efe41.html" title="Last updated on Jun 6, 2023, 12:14 PM UTC (81efe41)">Diff</a>

Spec config instance setting and clearing semantics

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/105.html" title="Last updated on Jun 14, 2023, 7:46 PM UTC (e3146d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/105/2d2a330...e3146d3.html" title="Last updated on Jun 14, 2023, 7:46 PM UTC (e3146d3)">Diff</a>

Fix visibility decl

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/106.html" title="Last updated on Jun 24, 2023, 7:11 PM UTC (176cbb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/106/376d4d0...176cbb5.html" title="Last updated on Jun 24, 2023, 7:11 PM UTC (176cbb5)">Diff</a>

Spec the beacon fetch integration

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/114.html" title="Last updated on Aug 23, 2023, 4:18 PM UTC (bf55809)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/114/7281202...xiaochen-z:bf55809.html" title="Last updated on Aug 23, 2023, 4:18 PM UTC (bf55809)">Diff</a>

Add attestations check to beacon sending algorithm.

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/JensenPaul/fenced-frame/pull/128.html" title="Last updated on Oct 9, 2023, 4:09 PM UTC (d1d3be6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/128/49fe518...JensenPaul:d1d3be6.html" title="Last updated on Oct 9, 2023, 4:09 PM UTC (d1d3be6)">Diff</a>

[spec] Fix indentation on a "for each" block

---

spec.bs

Addresses #160
***
<a href="https://pr-preview.s3.amazonaws.com/JensenPaul/fenced-frame/pull/161.html" title="Last updated on Jun 6, 2024, 1:33 PM UTC (6495120)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/161/4966a9e...JensenPaul:6495120.html" title="Last updated on Jun 6, 2024, 1:33 PM UTC (6495120)">Diff</a>

Spec deprecatedURNtoURL

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/175.html" title="Last updated on Aug 9, 2024, 9:27 PM UTC (81ae4f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/175/7889258...81ae4f4.html" title="Last updated on Aug 9, 2024, 9:27 PM UTC (81ae4f4)">Diff</a>

Spec: fix typo in ad component section

---

.github/workflows/build.yml

This should fix the spec builds that area breaking in CI.

Update build.yml to ubuntu-latest

---

spec.bs

PR #197 was merged prematurely, so these changes should cover the remaining two comments.
***
<a href="https://pr-preview.s3.amazonaws.com/VergeA/fenced-frame/pull/199.html" title="Last updated on Nov 11, 2024, 4:21 PM UTC (7fef624)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/199/a22434f...VergeA:7fef624.html" title="Last updated on Nov 11, 2024, 4:21 PM UTC (7fef624)">Diff</a>

Address WebRTC spec patch feedback from #197.

---

explainer/fenced_frames_with_local_unpartitioned_data_access.md

State that the feature is gated by “Block all third-party cookies” settings. This PR has been approved by CMA.

Explainer Update: Fenced Frame local unpartitioned data access UX setting update

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/pull/225.html" title="Last updated on Mar 26, 2025, 3:15 PM UTC (06b97f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/225/2eb05b7...06b97f3.html" title="Last updated on Mar 26, 2025, 3:15 PM UTC (06b97f3)">Diff</a>

Add Liam Brady as an editor

---

spec.bs

Fix #217.
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/219.html" title="Last updated on Mar 27, 2025, 6:30 PM UTC (9cba8a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/219/9e3e56c...xiaochen-z:9cba8a9.html" title="Last updated on Mar 27, 2025, 6:30 PM UTC (9cba8a9)">Diff</a>

link dns prefetch network revocation patch

---

spec.bs

Fix #218.
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/220.html" title="Last updated on Mar 27, 2025, 6:29 PM UTC (c9308c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/220/9e3e56c...xiaochen-z:c9308c4.html" title="Last updated on Mar 27, 2025, 6:29 PM UTC (c9308c4)">Diff</a>

link preconnect network revocation patch

---

explainer/fenced_frames_with_local_unpartitioned_data_access.md
spec.bs

State that Fenced Storage Read will be gated on the enrollment to the new API category.
***
<a href="https://pr-preview.s3.amazonaws.com/xiaochen-z/fenced-frame/pull/226.html" title="Last updated on Mar 31, 2025, 3:32 PM UTC (27c036e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/fenced-frame/226/6c59d71...xiaochen-z:27c036e.html" title="Last updated on Mar 31, 2025, 3:32 PM UTC (27c036e)">Diff</a>

Explainer Update: Fenced Storage Read enrollment
